apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud
  namespace: hanzo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/buffering.maxrequestbodybytes: "52428800"
spec:
  ingressClassName: hanzo
  rules:
    - host: cloud.hanzo.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud
                port:
                  number: 80
  tls:
    - hosts:
        - cloud.hanzo.ai
      secretName: cloud-tls
